/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithdrawImport } from './routes/withdraw'
import { Route as TransactionsImport } from './routes/transactions'
import { Route as MarketPricesImport } from './routes/market-prices'
import { Route as DepositCryptoImport } from './routes/deposit-crypto'
import { Route as DepositAudImport } from './routes/deposit-aud'
import { Route as CryptoImport } from './routes/crypto'
import { Route as IndexImport } from './routes/index'
import { Route as BuySellCryptoIdImport } from './routes/buy-sell.$cryptoId'

// Create/Update Routes

const WithdrawRoute = WithdrawImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsRoute = TransactionsImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRoute,
} as any)

const MarketPricesRoute = MarketPricesImport.update({
  id: '/market-prices',
  path: '/market-prices',
  getParentRoute: () => rootRoute,
} as any)

const DepositCryptoRoute = DepositCryptoImport.update({
  id: '/deposit-crypto',
  path: '/deposit-crypto',
  getParentRoute: () => rootRoute,
} as any)

const DepositAudRoute = DepositAudImport.update({
  id: '/deposit-aud',
  path: '/deposit-aud',
  getParentRoute: () => rootRoute,
} as any)

const CryptoRoute = CryptoImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BuySellCryptoIdRoute = BuySellCryptoIdImport.update({
  id: '/buy-sell/$cryptoId',
  path: '/buy-sell/$cryptoId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoImport
      parentRoute: typeof rootRoute
    }
    '/deposit-aud': {
      id: '/deposit-aud'
      path: '/deposit-aud'
      fullPath: '/deposit-aud'
      preLoaderRoute: typeof DepositAudImport
      parentRoute: typeof rootRoute
    }
    '/deposit-crypto': {
      id: '/deposit-crypto'
      path: '/deposit-crypto'
      fullPath: '/deposit-crypto'
      preLoaderRoute: typeof DepositCryptoImport
      parentRoute: typeof rootRoute
    }
    '/market-prices': {
      id: '/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof MarketPricesImport
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsImport
      parentRoute: typeof rootRoute
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawImport
      parentRoute: typeof rootRoute
    }
    '/buy-sell/$cryptoId': {
      id: '/buy-sell/$cryptoId'
      path: '/buy-sell/$cryptoId'
      fullPath: '/buy-sell/$cryptoId'
      preLoaderRoute: typeof BuySellCryptoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crypto': typeof CryptoRoute
  '/deposit-aud': typeof DepositAudRoute
  '/deposit-crypto': typeof DepositCryptoRoute
  '/market-prices': typeof MarketPricesRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/buy-sell/$cryptoId': typeof BuySellCryptoIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crypto': typeof CryptoRoute
  '/deposit-aud': typeof DepositAudRoute
  '/deposit-crypto': typeof DepositCryptoRoute
  '/market-prices': typeof MarketPricesRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/buy-sell/$cryptoId': typeof BuySellCryptoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/crypto': typeof CryptoRoute
  '/deposit-aud': typeof DepositAudRoute
  '/deposit-crypto': typeof DepositCryptoRoute
  '/market-prices': typeof MarketPricesRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/buy-sell/$cryptoId': typeof BuySellCryptoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crypto'
    | '/deposit-aud'
    | '/deposit-crypto'
    | '/market-prices'
    | '/transactions'
    | '/withdraw'
    | '/buy-sell/$cryptoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crypto'
    | '/deposit-aud'
    | '/deposit-crypto'
    | '/market-prices'
    | '/transactions'
    | '/withdraw'
    | '/buy-sell/$cryptoId'
  id:
    | '__root__'
    | '/'
    | '/crypto'
    | '/deposit-aud'
    | '/deposit-crypto'
    | '/market-prices'
    | '/transactions'
    | '/withdraw'
    | '/buy-sell/$cryptoId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CryptoRoute: typeof CryptoRoute
  DepositAudRoute: typeof DepositAudRoute
  DepositCryptoRoute: typeof DepositCryptoRoute
  MarketPricesRoute: typeof MarketPricesRoute
  TransactionsRoute: typeof TransactionsRoute
  WithdrawRoute: typeof WithdrawRoute
  BuySellCryptoIdRoute: typeof BuySellCryptoIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CryptoRoute: CryptoRoute,
  DepositAudRoute: DepositAudRoute,
  DepositCryptoRoute: DepositCryptoRoute,
  MarketPricesRoute: MarketPricesRoute,
  TransactionsRoute: TransactionsRoute,
  WithdrawRoute: WithdrawRoute,
  BuySellCryptoIdRoute: BuySellCryptoIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/crypto",
        "/deposit-aud",
        "/deposit-crypto",
        "/market-prices",
        "/transactions",
        "/withdraw",
        "/buy-sell/$cryptoId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/crypto": {
      "filePath": "crypto.tsx"
    },
    "/deposit-aud": {
      "filePath": "deposit-aud.tsx"
    },
    "/deposit-crypto": {
      "filePath": "deposit-crypto.tsx"
    },
    "/market-prices": {
      "filePath": "market-prices.tsx"
    },
    "/transactions": {
      "filePath": "transactions.tsx"
    },
    "/withdraw": {
      "filePath": "withdraw.tsx"
    },
    "/buy-sell/$cryptoId": {
      "filePath": "buy-sell.$cryptoId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
